### ISSUE TITLE
Suggestion for blog extension to allow simpler CSS-theming

### ISSUE THREAD

**Issue by glasen** [datenstrom/yellow#165] opened 2016-02-22 23:50 UTC
Hi,

Yesterday i made (copied) a theme for my private blog-site and stumbled over a small CSS-problem in the blog extension:

On a normal yellow-based website the footer is a div separate from the div "content main". The blog-plugin otherwise puts the footer into the div "content main" which means it makes it very difficult to generate a single and simple CSS-entry for the footer.

My work-around for this problem was to remove the snipped "footer" from the files "blog.html" und "blogpages.html" and place at the end of the files "content-blog.php" and "content-blogpages.php". With this workaround i can share my CSS-theme between my private blog and my universities website:

https://www.glasen-hardt.de -> Blog
https://homepages.thm.de/~sgls22/ -> University site (Normal static site)

Another thing i stumbled over is that "main" and "content" share the same div. Because "entry" is a child of "content" and "main" you cannot style a blog page the same way you style a normal page. 
With this setup it is impossible to put the blog-entries e.g. in the bordered white box without another white box around them. (Please see my sites for an example. It is a bit hard to explain).

I modified the files "content-blog.php" and "content-blogpages.php" and removed "main" from the outer div.

It's not a perfect solution but it works for my theme.

**Comment by wunderfeyd** [comment] 2016-02-24 23:05
I'm afraid I can't follow completely with the first issue. I checked against the [demo page](http://demo.datenstrom.se/blog/). There're all footers (on normal page, blog, blog page) outside the "content main" div. Are you able to preproduce the problem with a fresh setup containing the yellow core and the blog extension only?

I understand the second issue. Just a thought: What about replacing the content class in the outer div with a new blog class and add the content class to the inner entry div?
~~~
<div class="main blog">
  <div class="content entry">
  </div>
</div>
~~~
At least the naming would be right. What do you think? Would it be handy for you and other setups?

**Comment by glasen** [comment] 2016-02-25 12:03
Okay, the first problem was no problem. Maybe a changed something locally and the footer was moved to the content-div. With a fresh setup made from "yellow-master" it works as expected.

Your suggestion for the second problem sounds good. I tried it and it works for both of my pages without changing the CSS-code.

**Comment by wunderfeyd** [comment] 2016-02-25 23:40
@glasen: Thanks for your feedback and for testing again. I'll discuss this topic with @markseu the next days. Maybe we can use this class order by default but there might be some drawbacks I don't see at the moment. So we have to discuss and test beforehand.

**Comment by markseu** [comment] 2016-02-29 23:28
At the moment a normal page looks like:
```html
<div class="page default">
    <div class="header">...</div>
    <div class="content main">
        Page output goes in here
    </div>
    <div class="footer">...</div>
    </div>
</div>
```

At the moment a blog page looks like:

```html
<div class="page blog">
    <div class="header">...</div>
    <div class="content main">
        <div class="entry">... </div>    <------ Blog output is inside another div
    </div>
    <div class="footer">...</div>
    </div>
</div>
```

I suggest to put your Yellow theme on GitHub. Makes it easier to help with a bugfix, would that allow more people to use your theme. I understand that creating a theme from scratch is not an easy task and takes time. When more people contribute to Yellow we can all benefit from it.

**Comment by markseu** [comment] 2016-03-10 09:54
We should probably look into themes from other CMS and libraries, see if there's a pattern that can be used and allows easier theme development. There are for example Bootstrap, Pure and other open source projects to take a look at. Since there's no feedback I am closing this issue.

**Closed by markseu** 2016-03-10 09:54 UTC
