### ISSUE TITLE
contact form "from" & dmarc rejections

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#542] opened 2020-09-02 17:42 UTC
contact form uses senders email address as "from", which confuses dmarc filters...i.e: yahoo rejects mail not sent from its own domain, so anyone sending a contact form with yahoo address is rejected, possibly microsoft and gmail would go to spam due to their respective DMARC policies

yahoo: v=DMARC1; p=**reject;** pct=100; rua=mailto:dmarc_y_rua@yahoo.com;
microsoft: v=DMARC1; p=**reject**; pct=100; rua=mailto:d@rua.agari.com; ruf=mailto:d@ruf.agari.com; fo=1
gmail: v=DMARC1; p=none; sp=**quarantine**; rua=mailto:mailauth-reports@google.com

so customer comes to _example.com_ website, fills the contact form with customer@yahoo.com and yahoos DMARC check fails because email is originating from _example.com_ and not yahoo.com... therefore - email is rejected

is best practice to use own address as "from"?
and use customer address as reply-to..?
e.g:...

$mailTo = mb_encode_mimeheader("$author")." <$email>";
$mailSubject = mb_encode_mimeheader($this->yellow->page->get("title"));
$mailHeaders = mb_encode_mimeheader("From: $author")." <$email>\r\n";
$mailHeaders = mb_encode_mimeheader("Reply-To: $name")." <$from>\r\n";

**Comment by nzyeehaa** [comment] 2020-09-02 17:59
...not all email clients may respect the Reply-To field when we actually click "Reply"

**Comment by nzyeehaa** [comment] 2020-09-02 18:20
From [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.6.2)
The "Sender:" field specifies the mailbox of the agent responsible for the actual transmission of the message.
In all cases, the "From:" field SHOULD NOT contain any mailbox that does not belong to the author(s) of the message.

therefore...

$mailTo = mb_encode_mimeheader("$author")." <$email>";
$mailSubject = mb_encode_mimeheader($this->yellow->page->get("title"));
$mailHeaders = mb_encode_mimeheader("From: $name")." <$from>\r\n";
$mailHeaders = mb_encode_mimeheader("Sender: $author")." <$email>\r\n";
$mailHeaders = mb_encode_mimeheader("Reply-To: $name")." <$from>\r\n"; _{optional}_

may be the most politicaly correct version, and should work for the majority of mail clients

**Comment by nzyeehaa** [comment] 2020-09-03 09:55
further to the above...
with identical mail server settings...

yellow v 7.6 / contact v 7.3 sends fine with yahoo address
yellow v 8.9 / contact v 8.7 still awaiting confirmation
yellow v 8.11 / contact v 8.8 does **not** send with yahoo address

**Comment by markseu** [comment] 2020-09-03 13:11
Let me guess... your webmaster email address is your yahoo address? 

If this is true, than the problem is your webmaster email address and you can try the following:

1. If your website is hosted at `http://example.com` than use an email address with the same domain name, for example `webmaster@example.com`. Many service providers run both web server and mail server inside their own infrastructure, so there should never be any problem with mail sending and spam filtering. This is the recommended setup for the contact extension. 
2. If your website is hosted on a free hosting provider or one that doesn't come with an email address, then use a different email service than Yahoo. It's probably time to face the unpleasant news, that another service provider would work better.
3. Ask your email service provider if there's an authentication token that you can add to outgoing email headers. You have to extend the contact extension yourself or suggest the authentication token as a new idea. We don't have such a feature yet.

Let us know what you find out, hope this helps.

**Comment by nzyeehaa** [comment] 2020-09-03 14:33
@markseu hi mark, thanks for taking the time to respond.
- over three tested sites, 
- all are on the same server/ IP
- all use the same mail server / IP (they are all different domains)
- all sites have identical server/ mail server setup
- all share the same webmaster address, 
- all have an additional and different domain based email address setup for the contact form.
- all sites use DKIM SPF and DMARC with comparable settings
- all sites use different yellow and contact versions

+ currently **one** site **fails** if a site visitor **uses the contact form** and has a **yahoo address** (Yellow 8.11 / contact 8.8)
+ another site is awaiting a response from testing, but there has been no bounce email (yellow 8.9 / contact 8.7)
+ another site works fine with yahoo email address (yellow 7.6 / contact 7.3)

* I adjusted the failing site with...
`
$mailHeaders = mb_encode_mimeheader("From: $author")." <$email>\r\n";  
$mailHeaders = mb_encode_mimeheader("Reply-To: $name")." <$from>\r\n";
`
and while this is not technically correct implementation - there has been no bounce email using a yahoo address.

my reasoning suggests there is something in the contact form which is contributing to the email rejection, or moreover something that could be further optimised.

Yahoo has made bold use of DMARC rejection, as has microsoft, and even gmail "pushed the envelope" for a while.
part of the bounce message says 
`Unauthenticated email from yahoo.com is not accepted due to domain's DMARC policy. Please contact the administrator of yahoo.com domain if this was a legitimate mail.`

in the case of the contact form - the mail of course does not originate from yahoo... the mail is originating through a private domain

bear in mind this is one **visitor** to the site who happens to have a yahoo address ~ therefore every visitor using yahoo email will fail

**Comment by markseu** [comment] 2020-09-03 15:04
Let me repeat my previous assessment. I think the problem is the webmaster using a yahoo address, not the the visitor using a yahoo address. I recommend to configure a **non-yahoo email address** for the webmaster. You can also make your own contact extension, with your own workarounds for a specific email service provider.

**Comment by nzyeehaa** [comment] 2020-09-04 07:41
@markseu 
then you are wrong and you have missed some crucial information in the previous posts

the webmaster **is** a private domain
the _**visitor**_ is a yahoo address

further information...

```
if ($this->yellow->page->isExisting("author") && !$this->yellow->system->get("contactEmailRestriction")) {
            $author = $this->yellow->page->get("author");
        }
        if ($this->yellow->page->isExisting("email") && !$this->yellow->system->get("contactEmailRestriction")) {
            $email = $this->yellow->page->get("email");
        }
```
the above overrides the system.ini webmaster email when an author and email are set on the contact page

author and email are set in the contact page. Authors email is a **gmail** address

The problem exists when author is using a **gmail** address and the **visitor** is using yahoo
when these conditions exist - the email is bounced
(spf has include:_spf.google.com)

'''
//$mailHeaders = mb_encode_mimeheader("From: $name")." <$from>\r\n";
$mailHeaders = mb_encode_mimeheader("From: $author")." <$email>\r\n"; 
$mailHeaders = mb_encode_mimeheader("Reply-To: $name")." <$from>\r\n";
'''
fixes the initial problem and the mail is delivered, but it is not technically correct

the way it was originally set **is** technically correct - however a visitor using yahoo is the sender of the mail on another domain therefore it is unauthenticated, and it is rejected by yahoo's DKIM / SPF / DMARC policies
and i suspect the same will happen with microsoft, but havent tested it

There is no way to keep it technically correct **and** solve the problem...
this is a problem with **webforms** in general and the current state of anti-spam measures.

however the problem exists, and it will continue to affect yellow users.
with 3.9-4.5 billion email users in the world - at yahoo's famous data breach in 2013 - they had 3 billion accounts
even if there are only 10% of users that now have a yahoo address - it could still be 10% of your custom gone, and a bad reputation building.

drupal have an implementation to change any 'from' email to a root domain -no-reply email.
this also wont be technically correct - but it will aid in deliverability of webforms

**Comment by markseu** [comment] 2020-09-04 09:15
Have you tried to set an email that matches the domain name of your website?

**Comment by nzyeehaa** [comment] 2020-09-04 12:43
I have tried 19 hours worth of experiments to diagnose and find a way past it, as i have customers losing business, and bounce emails backing up.

in the case quoted... 
i can setup an email on the domain / server to receive the contact form email, and add a forwarder to gmail = fails
i can setup an email on the domain / server to receive the contact form email, and have gmail use pop3 to retrieve it = soft fails / spam
i can change "From" to a server domain (or Gmail) and set up "reply-to" and it works

> $mailHeaders = mb_encode_mimeheader("From: $author")." <$email>\r\n";
$mailHeaders = mb_encode_mimeheader("Reply-To: $name")." <$from>\r\n";

yahoo suggests
```
If you are sending on behalf of individuals, we recommend that you send mail from your own domain. You can set a Reply-To: header with their email address so that people can reply to the sharer instead of to you. Let’s pretend you are “sharing.example”:

Reply-to: “Example Sender” <example-sender@yahoo.com>

From: “Example Sender” <noreply@sharing.example>
```

again - while this is not technically correct as per RFC, 
both yahoo and microsoft will reject mail with their domains - that are not originating from their servers.

from a technical standpoint - the way the contact form is setup is correct.
from the evolving DMARC restrictions - change is urgently needed - or lose the contact form

**Comment by markseu** [comment] 2020-09-04 14:08
Have you tried to not forward emails -or- only to an email that matches the domain name of your website?

**Comment by nzyeehaa** [comment] 2020-09-07 02:42
yes, and in one word - **_deliverability_**

i live in the country. 
if i send a letter to mark in sweden, i write the letter, _sign the letter_, put my _return address_ on the back, put it in my (domain)mailbox and put a flag up.
the mailman comes, sees the flag, gets the letter, drops off any other mail, takes the letter to the post office, who sends it to sweden's post office for another mailman to deliver to mark, mark reads the mail and sees it is signed by me, and has my return address to reply to.(or if mark has moved - the letter can be returned to me so I know mark has moved and the letter was not delivered)

If i use a webform to write a letter, and put the letter in the (domain)mailbox but it can not go anywhere else because i have signed the letter and put my return address on it, the mailman can not pick up the letter, the letter can not get to sweden, mark can not get the letter and the entire system is broken.

mark would have to somehow know I have written a letter, then travel to New Zealand, find my house, open the mail box and read the letter.

for this webform - we are only talking about the **signature on the letter and the return address**. 

all yahoo is saying is that we cant use their pen to write the letter, and we cant say we are sending the letter through their post office (unless we are)- thats all **fair enough**.

essentially - a visitor to a website/webform is using the (domains) pen to write a letter and they put their own reply address on it...
simple...

the rest should be automatic and gauranteed - the letter should be delivered no matter what colour the mailbox is, who the mailman is, what brand of mail-car the mail man drives, or what language the post office speaks.

{spam excepted}

**Comment by markseu** [comment] 2020-09-10 08:50
To be honest we could claim that the contact extensions works within design limitations and close this issue, but I am more interest in solving people's problems than technical problems. At the end of the day, technology is made to solve people problems. Can you clarify why you're not using the recommended setup? Does your web hosting not provide email accounts? I have the feeling that there is something missing that I don't understand.

**Comment by datenstromse** [comment] 2020-09-14 08:11
Thanks for your feedback. I am afraid to say that we don't change this, not unless there is more demand. We can't promise if we may do something like this later. However we definitely appreciate the feedback. If you want to make a new extension, [go ahead and let us know if you need help](https://datenstrom.se/yellow/help/contributing-guidelines).

**Closed by datenstromse** 2020-09-14 08:11 UTC

**Comment by nzyeehaa** [comment] 2020-09-14 11:59
When you are sending email using mail() function in PHP, the mail is sent from your **web server**. Sometimes it may cause issues on sending an email and fails to deliver mail to the recipient. When you send an email via **SMTP**, email is sent from the **mail server** rather than the **web server.**

according to the guy that made swiftmail...

> In my experience -- and others' -- the mail() function is not particularly predictable, or helpful.
> 
> Quite notably, the mail() function behaves entirely differently between Linux and Windows servers. On linux it uses sendmail, but on Windows it uses SMTP. ...
> 
> Serious drawbacks when using this Transport are:
> 
> Unpredictable message headers
> Lack of feedback regarding delivery failures
> Lack of support for several plugins that require real-time delivery feedback
> It's a last resort, and we say that with a passion!

**therefore** in order to fix the non-deliverability / non-forwardability of the contact form...

- you would need to use authenticated SMTP details inputed for webmaster/author and use SMTP transport to activate the **MAIL server**
I.E: use PHPmailer
OR
 - the "from" field would need to be the webmaster/author email address - **NOT** the form fillers address
 OR
- use MSMTP or swiftmailer or zend_mail or PEAR or CURL 

and considering the last options require modifications to the server, you would need one of the first two.

ref:
https://www.lifewire.com/send-email-from-php-script-4764146
https://www.codexworld.com/send-html-email-php-gmail-smtp-phpmailer/
https://github.com/PHPMailer/PHPMailer
http://reusableforms.com/d/b/phpmailer-contact-form

**Comment by nzyeehaa** [comment] 2020-09-14 12:37
> If you’ve created a PHP mail form and find it’s not sending email, then it’s most often due to the FROM address the form is using in its headers.
> 
> **Emails should not be sent with a FROM address hosted somewhere else**. For example:
> 
> user@hotmail.com
> user@comcast.net
> user@gmail.com
> 
> For example, if you’re sending from a site called ‘example.com’, **the FROM address in your PHP Mail form** **_must be_** something like admin@example.com. 

[REF: dreamhost](https://help.dreamhost.com/hc/en-us/articles/215507068-Troubleshooting-PHP-mail-)
