### ISSUE TITLE
Antispam, Csv and Bundler don't work together

### ISSUE THREAD

**Issue by i-do** [datenstrom/yellow#514] opened 2020-05-10 04:36 UTC
@markseu, in previous case with audio tag I think something is broken on my lovely online radio. Today I see it's because some tags was blacklisted.

I guess Gallery and Slider plugins not worked by the same reason. 

Almost forget about not working Disqus plugin — same here, I think it's about some Disqus changes. Now I guess the reason is less far :) 

Disqus is not critical for me but not the Gallery and Slider, so I will very grateful for any fix it advice.

**Comment by BsNoSi** [comment] 2020-05-10 06:41
Some general changes of the last may cause this therefore this is a relevant information for helping you.

**Comment by markseu** [comment] 2020-05-10 15:38
I can't reproduce a problem with a new installation. Can you describe what's not working?

**Comment by markseu** [comment] 2020-05-17 13:19
Ping @i-do. Have any additional information for us? The more we know the better we can help.

**Comment by GiovanniSalmeri** [comment] 2020-05-17 13:40
As a side-note (or perhaps is this one of the problems?), I think I discovered a potentially blocking problem in Gallery. If gallery.js is in a bundle where the first script use the `"use strict";` declaration, this declaration seems to extend to the entire bundle, and gallery.js does not work because in the line 15 there is an undeclared variable. A simple `var el = thumbElements[i];` solves everything.

Perhaps it would be a good idea to review all the js scripts and to add to all of them a `"use strict";` declaration? Usually the modifications needed are trivial.

**Comment by markseu** [comment] 2020-05-17 14:52
If that's the source of the problem, then i suggest to remove "use strict" from all bundles.

**Comment by markseu** [comment] 2020-05-17 16:35
I updated the bundle extension and fixed the undeclared variable that you found, Giovanni.

**Comment by i-do** [comment] 2020-05-21 10:33
> Ping @i-do. Have any additional information for us? The more we know the better we can help.

Still trying to find some free time to clean install Yellow with all plugins I need one-by-one to check it out. 

I can tell one thing: [blogpost with gallery](https://4a0.im/blog/best-travel-backpack) still broken. Maybe I can give some more info if you can advice where can I get it?

**Comment by markseu** [comment] 2020-05-21 10:46
Could this be another extension?  I see the following JavaScript error in my browser:
```
TypeError: window.addEventListener is not a function. 
(In 'window.addEventListener("DOMContentLoaded",initAntispamFromDOM,!1)', 'window.addEventListener' is undefined)
```

**Comment by i-do** [comment] 2020-05-21 10:52
> Could this be another extension? I see the following JavaScript error in my browser:
> 
> ```
> TypeError: window.addEventListener is not a function. 
> (In 'window.addEventListener("DOMContentLoaded",initAntispamFromDOM,!1)', 'window.addEventListener' is undefined)
> ```

@markseu, can't say :)

But you can see the log:
`2019-03-17 13:51:25 info Update extension 'Antispam 0.8.3'
2019-03-17 13:51:25 info Update extension 'Audio 0.8.3'
2019-03-17 13:51:25 info Update extension 'Bundle 0.8.3'
2019-03-17 13:51:25 info Update extension 'Command 0.8.3'
2019-03-17 13:51:25 info Update extension 'Edit 0.8.3'
2019-03-17 13:51:25 info Update extension 'Motd 0.8.3'
2019-03-17 13:51:25 info Update extension 'Private 0.8.3'
2019-03-17 13:51:25 info Update extension 'Random 0.8.3'
2019-03-21 23:41:18 info Install extension 'Csv 0.8.3'
2019-03-28 02:36:26 info Update extension 'Bundle 0.8.4'
2019-03-28 02:36:26 info Update extension 'Command 0.8.4'
2019-03-28 02:36:26 info Update extension 'Edit 0.8.5'
2019-03-28 02:36:26 info Update extension 'English 0.8.4'
2019-03-28 02:36:26 info Update extension 'Feed 0.8.3'
2019-03-28 02:36:26 info Update extension 'German 0.8.4'
2019-03-28 02:36:26 info Update extension 'Markdown 0.8.4'
2019-03-28 02:36:26 info Update extension 'Russian 0.8.4'
2019-03-28 02:36:26 info Update extension 'Update 0.8.5'
2019-03-28 02:36:26 info Update extension 'Wiki 0.8.3'
2019-04-07 05:25:27 info Update extension 'Command 0.8.5'
2019-04-07 05:25:27 info Update extension 'Edit 0.8.6'
2019-04-07 05:25:27 info Update extension 'English 0.8.5'
2019-04-07 05:25:27 info Update extension 'German 0.8.5'
2019-04-13 00:53:43 info Update extension 'Command 0.8.6'
2019-04-13 00:53:43 info Update extension 'Core 0.8.4'
2019-04-13 00:53:43 info Update extension 'Edit 0.8.7'
2019-04-13 00:53:43 info Update extension 'Update 0.8.7'
2019-04-19 01:29:47 info Update extension 'English 0.8.6'
2019-04-19 01:29:47 info Update extension 'German 0.8.6'
2019-04-19 01:29:47 info Update extension 'Russian 0.8.6'
2019-04-24 01:06:11 info Update extension 'Blog 0.8.3'
2019-04-24 01:06:11 info Update extension 'Wiki 0.8.4'
2019-05-12 02:15:27 info Update extension 'Bundle 0.8.5'
2019-05-12 02:15:27 info Update extension 'Csv 0.8.5'
2019-05-12 02:15:27 info Update extension 'English 0.8.7'
2019-05-12 02:15:27 info Update extension 'German 0.8.7'
2019-05-12 02:15:27 info Update extension 'Russian 0.8.7'
2019-05-17 01:04:47 info Update extension 'Update 0.8.8'
2019-05-24 13:46:46 info Update extension 'Markdown 0.8.5'
2019-05-25 03:10:58 info Update extension 'Markdown 0.8.6'
2019-05-28 22:00:22 info Update extension 'Markdown 0.8.7'
2019-05-30 23:14:48 info Update extension 'Blog 0.8.4'
2019-05-30 23:14:48 info Update extension 'Feed 0.8.4'
2019-06-02 02:23:55 info Update extension 'Edit 0.8.8'
2019-06-02 02:23:55 info Update extension 'English 0.8.8'
2019-06-02 02:23:55 info Update extension 'German 0.8.8'
2019-06-02 02:23:55 info Update extension 'Russian 0.8.8'
2019-06-07 16:09:47 info Update extension 'Core 0.8.5'
2019-06-07 16:09:47 info Update extension 'Edit 0.8.10'
2019-06-07 16:09:47 info Update extension 'English 0.8.10'
2019-06-07 16:09:47 info Update extension 'German 0.8.10'
2019-06-07 16:09:47 info Update extension 'Markdown 0.8.8'
2019-06-07 16:09:47 info Update extension 'Russian 0.8.10'
2019-06-07 16:09:47 info Update extension 'Update 0.8.9'
2019-06-10 20:46:10 info Update extension 'Edit 0.8.11'
2019-06-10 20:46:10 info Update extension 'English 0.8.11'
2019-06-10 20:46:10 info Update extension 'German 0.8.11'
2019-06-10 20:46:10 info Update extension 'Russian 0.8.11'
2019-07-01 01:29:16 info Update extension 'English 0.8.12'
2019-07-01 01:29:16 info Update extension 'German 0.8.12'
2019-07-01 01:29:16 info Update extension 'Russian 0.8.12'
2019-07-01 01:29:16 info Update extension 'Wiki 0.8.5'
2019-09-02 04:53:10 info Update extension 'Csv 0.8.6'
2019-09-28 23:31:49 info Update extension 'Core 0.8.6'
2019-09-28 23:31:49 info Update extension 'Edit 0.8.12'
2019-12-16 07:27:18 info Update extension 'Bundle 0.8.6'
2019-12-16 07:27:18 info Update extension 'Command 0.8.8'
2019-12-16 07:27:18 info Update extension 'Core 0.8.8'
2019-12-16 07:27:18 info Update extension 'Draft 0.8.3'
2019-12-16 07:27:18 info Update extension 'Edit 0.8.13'
2019-12-16 07:27:18 info Update extension 'English 0.8.14'
2019-12-16 07:27:18 info Update extension 'Feed 0.8.5'
2019-12-16 07:27:18 info Update extension 'Gallery 0.8.4'
2019-12-16 07:27:18 info Update extension 'German 0.8.14'
2019-12-16 07:27:18 info Update extension 'Image 0.8.4'
2019-12-16 07:27:18 info Update extension 'Markdown 0.8.10'
2019-12-16 07:27:18 info Update extension 'Private 0.8.5'
2019-12-16 07:27:18 info Update extension 'Russian 0.8.14'
2019-12-16 07:27:18 info Update extension 'Slider 0.8.3'
2019-12-16 07:27:18 info Update extension 'Update 0.8.11'
2019-12-29 04:49:32 info Update extension 'Audio 0.8.4'
2019-12-29 04:49:32 info Update extension 'Bundle 0.8.7'
2019-12-29 04:49:32 info Update extension 'Command 0.8.10'
2019-12-29 04:49:32 info Update extension 'Csv 0.8.7'
2019-12-29 04:49:32 info Update extension 'Edit 0.8.14'
2019-12-29 04:49:32 info Update extension 'Feed 0.8.6'
2019-12-29 04:49:32 info Update extension 'Markdown 0.8.11'
2019-12-29 04:49:32 info Update extension 'Update 0.8.12'
2020-01-03 17:35:47 info Update extension 'Edit 0.8.15'
2020-01-03 17:35:47 info Update extension 'Update 0.8.14'
2020-01-05 17:10:15 info Update extension 'Core 0.8.9'
2020-01-05 17:10:15 info Update extension 'English 0.8.15'
2020-01-05 17:10:15 info Update extension 'German 0.8.15'
2020-01-05 17:10:15 info Update extension 'Russian 0.8.15'
2020-01-08 01:08:30 info Update extension 'Edit 0.8.16'
2020-01-08 01:08:30 info Update extension 'Image 0.8.5'
2020-01-11 09:30:01 info Update extension 'Edit 0.8.17'
2020-01-11 09:30:01 info Update extension 'English 0.8.16'
2020-01-11 09:30:01 info Update extension 'German 0.8.16'
2020-01-11 09:30:01 info Update extension 'Russian 0.8.16'
2020-01-16 02:04:41 info Update extension 'Core 0.8.10'
2020-01-16 02:04:41 info Update extension 'Edit 0.8.18'
2020-01-16 02:04:41 info Update extension 'English 0.8.17'
2020-01-16 02:04:41 info Update extension 'German 0.8.17'
2020-01-16 02:04:41 info Update extension 'Russian 0.8.17'
2020-01-16 02:04:41 info Update extension 'Update 0.8.15'
2020-01-17 16:55:19 info Update extension 'Edit 0.8.19'
2020-01-17 16:55:19 info Update extension 'Private 0.8.6'
2020-02-01 11:32:27 info Update extension 'Edit 0.8.20'
2020-02-05 17:33:59 info Update extension 'Update 0.8.16'
2020-02-12 16:53:24 info Update extension 'Edit 0.8.21'
2020-02-12 16:53:24 info Update extension 'English 0.8.18'
2020-02-12 16:53:24 info Update extension 'German 0.8.18'
2020-02-12 16:53:24 info Update extension 'Image 0.8.6'
2020-02-12 16:53:24 info Update extension 'Russian 0.8.18'
2020-03-07 17:58:03 info Update extension 'Blog 0.8.5'
2020-03-07 17:58:03 info Update extension 'Edit 0.8.22'
2020-03-07 17:58:03 info Update extension 'English 0.8.19'
2020-03-07 17:58:03 info Update extension 'Feed 0.8.7'
2020-03-07 17:58:03 info Update extension 'German 0.8.19'
2020-03-07 17:58:03 info Update extension 'Image 0.8.7'
2020-03-07 17:58:03 info Update extension 'Markdown 0.8.12'
2020-03-07 17:58:03 info Update extension 'Russian 0.8.19'
2020-03-07 17:58:03 info Update extension 'Update 0.8.17'
2020-03-07 19:27:23 info Install extension 'Core 0.8.11'
2020-03-09 12:44:03 info Update extension 'Csv 0.8.8'
2020-03-12 01:28:14 info Update extension 'Bundle 0.8.9'
2020-03-12 01:28:14 info Update extension 'Command 0.8.11'
2020-03-12 01:28:14 info Update extension 'Disqus 0.8.3'
2020-03-12 01:28:14 info Update extension 'Edit 0.8.24'
2020-03-12 01:28:14 info Update extension 'Update 0.8.18'
2020-03-14 14:33:53 info Update extension 'Blog 0.8.5'
2020-03-19 01:28:58 info Install extension 'Quiz 0.8.10'
2020-03-27 20:35:44 info Update extension 'Antispam 0.8.4'
2020-05-04 09:30:32 info Update extension 'Audio 0.8.5'
2020-05-05 04:56:52 info Install extension 'Slider 0.8.3'
2020-05-05 04:57:18 info Update extension 'Blog 0.8.5'
2020-05-10 03:38:50 info Update extension 'Core 0.8.12'
2020-05-17 19:02:02 info Update extension 'Bundle 0.8.10'
2020-05-17 19:02:02 info Update extension 'Edit 0.8.25'
2020-05-17 19:02:02 info Update extension 'Gallery 0.8.5'
2020-05-20 12:29:36 info Update extension 'Command 0.8.12'
`

**Comment by markseu** [comment] 2020-05-21 11:19
I checked your website again and see that the first two extensions in the bundle are:
```
/* antispam.js */
/* csv.js */
```

The JavaScript error occurs there, so maybe one of them doesn't play nice with the rest. Can you remove those two extensions?

**Comment by i-do** [comment] 2020-05-21 12:48
> I checked your website again and see that the first two extensions in the bundle are:
> 
> ```
> /* antispam.js */
> /* csv.js */
> ```
> 
> The JavaScript error occurs there, so maybe one of them doesn't play nice with the rest. Can you remove those two extensions?

Yes, removing this extensions fix the gallery.

**Comment by markseu** [comment] 2020-05-21 13:13
@schulle4u: Can you have a look please? Antispam, Csv and Bundler don't work together.

**Comment by schulle4u** [comment] 2020-05-21 17:08
@i-do Can you please download [this csv.php](https://github.com/schulle4u/yellow-extensions-schulle4u/raw/master/csv/csv.php) and upload it into your `system/extensions` directory? Then add `CsvFilter: 0` to `system/settings/system.ini` and check if the error still occurs. Some of the table filtering functions appear to be broken when used together with the bundle extension, though I'm not sure why. I remember to have tested this successfully when it was released.

**Comment by i-do** [comment] 2020-05-21 17:39
> @i-do Can you please download [this csv.php](https://github.com/schulle4u/yellow-extensions-schulle4u/raw/master/csv/csv.php) and upload it into your `system/extensions` directory? Then add `CsvFilter: 0` to `system/settings/system.ini` and check if the error still occurs. 

With new csv.php works well both with and without Filter settings adding. 
I've checked with real csv-data and it works like a charm.

**Comment by schulle4u** [comment] 2020-05-22 14:00
OK I think the problem is now fixed. The bundle extension seems to have issues if a javascript file contains an Immediately-Invoked Function Expression (IIFE) like `(function(document) {  }(document));`. Removing this expression solves the problem. I don't fully understand the purpose, but the rest of the functions are still working without it. Please update the CSV extension.

**Comment by markseu** [comment] 2020-05-23 17:58
Thank you @schulle4u. I can confirm that it works in a new installation.

**Closed** 2020-06-02 02:04 UTC
