### ISSUE TITLE
Development History in One Place

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#553] opened 2020-10-08 04:39 UTC
I am "Yellow part time customizer" using spare project time with variable time space between other projects I have to do. Therefore I regularly miss updates "in between" which leads regularly to very gruelling sessions upgrading existing sites.

For me it would be very helpful to have a "changes diary" of the versions: New, changed, deprecated, removed. Simply to have an idea why things that worked perfectly are nonfunctional or "show stopper" after an update.

It is very time consuming to install previous an new versions side by side comparing them file by file and go into deep to understand what may be the reason for failure. 

The requirements for such a document would be low. Just a few key points, what has changed where, perhaps with a short "why", would help people like me, who are not part of the constant development, to find out if time can be invested in Yellow again. Above all, there would be more time for new things instead of chasing after old ones.

A "latest first" list of changes would allow the quick identification of possible problems, because it would make the gap between "then" and "now" very quickly tangible.

**Comment by datenstromse** [comment] 2020-10-08 06:30
Duplicate of #554

**Closed by datenstromse** 2020-10-08 06:30 UTC
