### ISSUE TITLE
draft plugin

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#343] opened 2018-07-05 07:42 UTC
i love the draft plugin. 
end user marks items as `Status: draft` until finished - then removes the status which makes page live.
..or wants to keep notes to themselves, make a page, set `Status: draft `and bingo. 
website viewers can't see it, but when they login - they can find it easily by searching `Status: draft`

However,
if the plugin is removed - all those confidential pages become live!
The core already has status: hidden
anybody else think that status:draft should be part of that core ?

**Comment by BsNoSi** [comment] 2018-07-05 10:46
As far as I know, the core has a `status: hidden` option. I am not sure if there are and if which differences `hidden`and|or `draft` have. 

`Hidden`is shown as well as soon as you are logged in (and know the page address) and is `not found` if you click a link without being logged in.

Depending to this if they behave identical except the `status` identifier, the plugin `draft`maybe obsolete or – to answer the question – is still implemented.

**Comment by nzyeehaa** [comment] 2018-07-07 12:32
@BsNoSi  - thats correct - `status: hidden` is part of the core.
If a page is hidden - you can not use search to find it... even if you are logged in
If you know the link - you can access the page - only if you are logged in.
Therefore pages are hidden unless you are the webmaster accessing the file system, or can remember the link.

The `Status: draft` requires a **plugin** and draft pages are hidden from general website viewers.
If you are logged in you can search for `Status: draft` and it will return all draft pages. 

They are both very beneficial - and both have separate functions.
However the problem being discussed is whether the draft should be merged with the core.
- if I work on a site and mark a page as Status: draft - but dont yet have the plugin installed - the page will be public
- if the plugin is ever uninstalled - all draft pages will automatically be shown on the website

@markseu - it looks like there is an error in the router/search plugin - when logged in, search for `Status:hidden` and it returns every page. search for `Status: hidden` (with a space) returns no pages -- they should both return no pages

**Comment by BsNoSi** [comment] 2018-07-08 11:29
@nzyeehaa - thanks for explanation. I did not know this difference but I can see the benefit of both. I agree that this should possibly put together in the core. I think, this reduces code and makes it easier to handle additional status, i.e. "admin" that can only be edited by the administrator set in the config.ini (just an idea of a possible extend of functionality.

**Comment by datenstromse** [comment] 2018-07-10 09:04
Duplicate of #304

**Closed by datenstromse** 2018-07-10 09:04 UTC
