### ISSUE TITLE
Fatal error: Call to undefined method YellowContent::shared() after update

### ISSUE THREAD

**Issue by bpgs** [datenstrom/yellow#559] opened 2020-10-19 08:13 UTC
Recently I described an issue on my yellow  [localhost](https://github.com/datenstrom/yellow/issues/549). It was resolved with     core.php 0.8.22/0.8.16. This morning I've that there is a new update to  core.php 0.8.23/0.8.16. This Update leads to the following result (Windows 7/localhost):
`Fatal error: Uncaught Error: Call to undefined method YellowContent::shared() in H:\xampp-webs\one-reisebilder\www\system\layouts\header.html:43 Stack trace: #0 H:\xampp-webs\one-reisebilder\www\system\extensions\core.php(667): require() #1 H:\xampp-webs\one-reisebilder\www\system\extensions\core.php(337): YellowPage->includeLayout('header') #2 H:\xampp-webs\one-reisebilder\www\system\layouts\default.html(1): YellowCore->layout('header') #3 H:\xampp-webs\one-reisebilder\www\system\extensions\core.php(667): require('H:\\xampp-webs\\o...') #4 H:\xampp-webs\one-reisebilder\www\system\extensions\core.php(649): YellowPage->includeLayout('default') #5 H:\xampp-webs\one-reisebilder\www\system\extensions\core.php(600): YellowPage->parsePageLayout('default') #6 H:\xampp-webs\one-reisebilder\www\system\extensions\core.php(199): YellowPage->parsePage() #7 H:\xampp-webs\one-reisebilder\www\system\extensions\core.php(150): YellowCore->sendPage() #8 H:\xampp-webs\one-reisebilder\www\system\extensions\edit.php(688): YellowCore->processR in H:\xampp-webs\one-reisebilder\www\system\layouts\header.html on line 43`

If I try the same with my productive installation I get only an empty screen.

**Comment by markseu** [comment] 2020-10-19 08:18
Can you check if there are errors in your `system/extensions/yellow.log`?

**Comment by bpgs** [comment] 2020-10-19 09:29
No there are none. The recent lines of the yellow.log are
```
2020-10-19 09:20:42 info Update extension 'Blog 0.8.12'
2020-10-19 09:20:42 info Update extension 'Core 0.8.23'
2020-10-19 09:20:42 info Update extension 'Markdown 0.8.16'
2020-10-19 09:20:42 info Update extension 'Update 0.8.35'
2020-10-19 09:20:42 info Update extension 'Wiki 0.8.13'

```

**Comment by markseu** [comment] 2020-10-19 09:47
The website update should have automatically converted layout files to the new API. You can also do this manually.

For example open file `system/layouts/header.html` and look for:
```
<?php if ($page = $this->yellow->content->shared("header")) $this->yellow->page->setPage("header", $page) ?>		 <?php echo $this->yellow->page->getPage("header")->getContent() ?>
<?php if ($this->yellow->page->isPage("header")) echo $this->yellow->page->getPage("header")->getContent() ?>
```

... then replace with:

```
<?php echo $this->yellow->page->getPage("header")->getContent() ?>
```

You can also copy/paste the default layout files, see https://github.com/datenstrom/yellow/tree/master/system/layouts.

I am not sure what went wrong with the automatic update, hope this helps.

**Comment by i-do** [comment] 2020-10-22 17:22
Have the same issue.
Already fixed [by using this advice](https://github.com/datenstrom/yellow/issues/559#issuecomment-711948640).

**Comment by markseu** [comment] 2020-10-22 19:17
Were there any errors in your log file?

**Comment by i-do** [comment] 2020-10-22 20:06
> Were there any errors in your log file?

Mark, no, nothing in the log, just info about modules installed.
But I have empty start page here, It was the logged user's header only and empty space below.

**Comment by JetGum** [comment] 2020-10-22 20:40
Same here. after updating to the latest core, under WSL-System.

Strangely enough, some pages work, others don't. 

> 2020-10-22 19:52:24 info Update extension 'Bundle 0.8.16'
> 2020-10-22 19:52:24 info Update extension 'Command 0.8.24'
> 2020-10-22 19:52:24 info Update extension 'Core 0.8.24'
> 2020-10-22 19:52:24 info Update extension 'Fontawesome 0.8.7'
> 2020-10-22 19:52:24 info Update extension 'Image 0.8.10'
> 2020-10-22 19:52:24 info Update extension 'Markdown 0.8.16'
> 2020-10-22 19:52:24 info Update extension 'Update 0.8.36'

This is my header that worked until before the update.

![image](https://user-images.githubusercontent.com/48367334/96927357-383ca000-14b7-11eb-8f9a-7459d5ee581c.png)

**Comment by markseu** [comment] 2020-10-23 09:02
I can't reproduce the problem. I tested an update from 0.8.13 to 0.8.16 on Windows 10 + XAMPP. 

Jetgum if you're stuck with a broken website, [see advice above](https://github.com/datenstrom/yellow/issues/559#issuecomment-711948640).

**Comment by JetGum** [comment] 2020-10-24 15:20
Hi, I am still stuck...

I have 2 languages in the content folder:  /content/1-en and /content/2-de.

My settings in system.ini:
Language: en
Layout: default
CoreMultiLanguageMode: 1

I created individual layout files for the English pages: default-en.html, header-en.html, footer-en.html and navigation-tree-en.html.

In my header-en.html, I include the English navigation via

`<header> <?php $this->yellow->layout("navigation-tree-en") ?> </header> `

But there is no frontend output for `<?php $this->yellow->layout("navigation-tree-en") ?>`, output stops after `<header>`. Result is a blank page.

If I change ("navigation-tree-en") to simple ("navigation-tree") (which in my case is the German navigation), output is fine.

Cheers,

Carsten

**Comment by markseu** [comment] 2020-10-25 14:06
As a general advice for developers that are stuck, [have a look at API changes](https://github.com/datenstrom/yellow/issues/526). If you're not sure what causes layout problems, I would [activate the debug mode](https://datenstrom.se/yellow/help/troubleshooting#system-diagnostics). This will do two things. First activate PHP's `display_errors` and secondly tell Datenstrom Yellow to show exactly what's going on.

As for the original problem, I still can't figure out what causes leftover `YellowContent::shared()` for some users. If the updater doesn't have sufficient write permissions, then there would be an error in the log file. If the updater has sufficient write permissions, then layout files would be converted. Not sure what's happening, I wasn't able to reproduce it on Mac or Windows. If anyone has an idea how to narrow down this problem, let us know.

@schulle4u @GiovanniSalmeri did you encounter this problem during update?

**Comment by schulle4u** [comment] 2020-10-25 15:10
I'm still waiting for some extension updates and therefore haven't updated all my sites yet. But on a few test installs I couldn't reproduce this problem.

**Comment by JetGum** [comment] 2020-10-25 16:54
Sorry, but current core.php and https://datenstrom.se/yellow/help/troubleshooting#system-diagnostics do not correlate.
Where should I activate a debug mode in current core.php?

**Comment by JetGum** [comment] 2020-10-25 17:20
In Format-Extension, "getTextArgs" needs to be changed to getTextArguments" (format.php, line 20).

**Comment by herula** [comment] 2020-11-11 11:13
First of all, I like yellow very much and appreciate your work. Thank you. But updating is no fun at all. For the second time I have to do a new install because updating is killing my websites. My wiki with the beautiful but no longer maintained theme "Helsinki" says "server error" and it's not possible to log in anymore. A second website looks good after update, but no logins are possible and the system/settings directory is missing.  Yellow.log shows no errors:
2020-11-11 11:43:36 info Update extension 'Berlin 0.8.10'
2020-11-11 11:43:36 info Update extension 'Bundle 0.8.17'
2020-11-11 11:43:36 info Update extension 'Command 0.8.25'
2020-11-11 11:43:36 info Update extension 'Core 0.8.30'
2020-11-11 11:43:36 info Update extension 'Edit 0.8.38'
2020-11-11 11:43:36 info Update extension 'English 0.8.25'
2020-11-11 11:43:36 info Update extension 'French 0.8.25'
2020-11-11 11:43:36 info Update extension 'Gallery 0.8.10'
2020-11-11 11:43:36 info Update extension 'German 0.8.25'
2020-11-11 11:43:36 info Update extension 'Image 0.8.11'
2020-11-11 11:43:36 info Update extension 'Markdown 0.8.16'
2020-11-11 11:43:36 info Update extension 'Stockholm 0.8.10'
2020-11-11 11:43:36 info Update extension 'Ticker 0.8.9'
2020-11-11 11:43:36 info Update extension 'Update 0.8.42'
2020-11-11 10:43:37 info Convert settings files
2020-11-11 11:48:47 info Convert settings files
2020-11-11 11:51:04 info Convert settings files
2020-11-11 11:54:01 info Convert settings files
Thank you, Frank

**Comment by markseu** [comment] 2020-11-11 14:15
Just says "server error" and nothing more?

**Comment by herula** [comment] 2020-11-11 14:43
Yes. That's all: https://wornath.de/web/yellow-update

**Comment by markseu** [comment] 2020-11-11 14:46
Can you show the log file for this server?

**Comment by herula** [comment] 2020-11-11 15:37
Wed Nov 11 15:28:04.136989 2020] [php7:warn] [pid 26754] [client 87.123.238.248:60936] PHP Warning:  Illegal offset type in /var/www/wornath.de/wiki/system/extensions/core.php on line 3478, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:28:04.144083 2020] [php7:warn] [pid 26754] [client 87.123.238.248:60936] PHP Warning:  Illegal offset type in /var/www/wornath.de/wiki/system/extensions/core.php on line 3478, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:28:04.154401 2020] [php7:notice] [pid 26754] [client 87.123.238.248:60936] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:28:04.154614 2020] [php7:notice] [pid 26754] [client 87.123.238.248:60936] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:28:04.154844 2020] [php7:error] [pid 26754] [client 87.123.238.248:60936] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/error.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('error')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('error')\n#9 /var/www/wornath.de/wiki/system/ext in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:28:10.826585 2020] [php7:notice] [pid 26603] [client 87.123.238.248:60946] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14
[Wed Nov 11 15:28:10.829051 2020] [php7:notice] [pid 26603] [client 87.123.238.248:60946] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15
[Wed Nov 11 15:28:10.831325 2020] [php7:error] [pid 26603] [client 87.123.238.248:60946] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/wiki.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('wiki')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('wiki')\n#9 /var/www/wornath.de/wiki/system/extens in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15
[Wed Nov 11 15:28:22.628561 2020] [php7:notice] [pid 28676] [client 87.123.238.248:60950] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:28:22.628726 2020] [php7:notice] [pid 28676] [client 87.123.238.248:60950] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:28:22.628903 2020] [php7:error] [pid 28676] [client 87.123.238.248:60950] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/wiki.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('wiki')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('wiki')\n#9 /var/www/wornath.de/wiki/system/extens in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:31:43.451138 2020] [php7:warn] [pid 28205] [client 87.123.238.248:32776] PHP Warning:  Illegal offset type in /var/www/wornath.de/wiki/system/extensions/core.php on line 3478, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:31:43.451319 2020] [php7:warn] [pid 28205] [client 87.123.238.248:32776] PHP Warning:  Illegal offset type in /var/www/wornath.de/wiki/system/extensions/core.php on line 3478, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:31:43.461041 2020] [php7:notice] [pid 28205] [client 87.123.238.248:32776] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:31:43.461173 2020] [php7:notice] [pid 28205] [client 87.123.238.248:32776] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:31:43.461381 2020] [php7:error] [pid 28205] [client 87.123.238.248:32776] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/error.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('error')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('error')\n#9 /var/www/wornath.de/wiki/system/ext in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/edit/
[Wed Nov 11 15:48:46.001023 2020] [php7:notice] [pid 29228] [client 87.123.238.248:33208] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:46.009003 2020] [php7:notice] [pid 29228] [client 87.123.238.248:33208] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:46.009483 2020] [php7:error] [pid 29228] [client 87.123.238.248:33208] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/wikipages.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('wikipages')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('wikipages')\n#9 /var/www/wornath.de/wik in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:48.699235 2020] [php7:notice] [pid 29324] [client 87.123.238.248:33210] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:48.699387 2020] [php7:notice] [pid 29324] [client 87.123.238.248:33210] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:48.699543 2020] [php7:error] [pid 29324] [client 87.123.238.248:33210] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/wikipages.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('wikipages')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('wikipages')\n#9 /var/www/wornath.de/wik in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:50.447831 2020] [php7:notice] [pid 29229] [client 87.123.238.248:33212] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:50.450266 2020] [php7:notice] [pid 29229] [client 87.123.238.248:33212] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:50.452539 2020] [php7:error] [pid 29229] [client 87.123.238.248:33212] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/wikipages.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('wikipages')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('wikipages')\n#9 /var/www/wornath.de/wik in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:54.376345 2020] [php7:notice] [pid 28853] [client 87.123.238.248:33214] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:54.376501 2020] [php7:notice] [pid 28853] [client 87.123.238.248:33214] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:54.376722 2020] [php7:error] [pid 28853] [client 87.123.238.248:33214] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/wiki.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('wiki')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('wiki')\n#9 /var/www/wornath.de/wiki/system/extens in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:57.615077 2020] [php7:notice] [pid 29233] [client 87.123.238.248:33216] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:57.615237 2020] [php7:notice] [pid 29233] [client 87.123.238.248:33216] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:57.615423 2020] [php7:error] [pid 29233] [client 87.123.238.248:33216] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/wiki.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('wiki')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('wiki')\n#9 /var/www/wornath.de/wiki/system/extens in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:59.116312 2020] [php7:notice] [pid 29228] [client 87.123.238.248:33222] PHP Notice:  Undefined index: query in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 14, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:59.116447 2020] [php7:notice] [pid 29228] [client 87.123.238.248:33222] PHP Notice:  Undefined property: YellowCore::$extensions in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/
[Wed Nov 11 15:48:59.116647 2020] [php7:error] [pid 29228] [client 87.123.238.248:33222] PHP Fatal error:  Uncaught Error: Call to a member function isExisting() on null in /var/www/wornath.de/wiki/system/layouts/navigation-search.html:15\nStack trace:\n#0 /var/www/wornath.de/wiki/system/extensions/core.php(670): require()\n#1 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('navigation-sear...')\n#2 /var/www/wornath.de/wiki/system/layouts/header.html(27): YellowCore->layout('navigation-sear...')\n#3 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#4 /var/www/wornath.de/wiki/system/extensions/core.php(340): YellowPage->includeLayout('header')\n#5 /var/www/wornath.de/wiki/system/layouts/wiki.html(1): YellowCore->layout('header')\n#6 /var/www/wornath.de/wiki/system/extensions/core.php(670): require('/var/www/wornat...')\n#7 /var/www/wornath.de/wiki/system/extensions/core.php(652): YellowPage->includeLayout('wiki')\n#8 /var/www/wornath.de/wiki/system/extensions/core.php(603): YellowPage->parsePageLayout('wiki')\n#9 /var/www/wornath.de/wiki/system/extens in /var/www/wornath.de/wiki/system/layouts/navigation-search.html on line 15, referer: https://wornath.de/wiki/

**Comment by markseu** [comment] 2020-11-11 15:45
Can you show the `system/extensions/yellow.log` for this server?

**Comment by herula** [comment] 2020-11-11 16:00
2020-01-02 22:54:43 info Update extension 'Search 0.8.5'
2020-01-02 22:54:43 info Update extension 'Stockholm 0.8.6'
2020-01-02 22:54:43 info Update extension 'Update 0.8.12'
2020-03-08 22:22:17 info Update extension 'Core 0.8.11'
2020-03-08 22:22:17 info Update extension 'Edit 0.8.22'
2020-03-08 22:22:17 info Update extension 'English 0.8.19'
2020-03-08 22:22:17 info Update extension 'French 0.8.19'
2020-03-08 22:22:17 info Update extension 'German 0.8.19'
2020-03-08 22:22:17 info Update extension 'Image 0.8.7'
2020-03-08 22:22:17 info Update extension 'Markdown 0.8.12'
2020-03-08 22:22:17 info Update extension 'Meta 0.8.11'
2020-03-08 22:22:17 info Update extension 'Private 0.8.6'
2020-03-08 22:22:17 info Update extension 'Stockholm 0.8.7'
2020-03-08 22:22:17 info Update extension 'Update 0.8.17'
2020-03-10 18:46:41 info Update extension 'Search 0.8.5'
2020-08-27 15:47:41 info Update extension 'Command 0.8.22'
2020-08-27 15:47:41 info Update extension 'Core 0.8.19'
2020-08-27 15:47:42 info Update extension 'Edit 0.8.35'
2020-08-27 15:47:42 info Update extension 'Update 0.8.31'
2020-09-10 18:24:35 info Update extension 'Bundle 0.8.15'
2020-09-10 18:24:35 info Update extension 'Core 0.8.20'
2020-09-10 18:24:35 info Update extension 'English 0.8.24'
2020-09-10 18:24:35 info Update extension 'French 0.8.24'
2020-09-10 18:24:35 info Update extension 'German 0.8.24'
2020-09-10 18:24:35 info Update extension 'Image 0.8.9'
2020-09-10 18:24:35 info Update extension 'Markdown 0.8.15'
2020-09-10 18:24:35 info Update extension 'Meta 0.8.14'
2020-09-10 18:24:35 info Update extension 'Private 0.8.7'
2020-09-10 18:24:35 info Update extension 'Search 0.8.10'
2020-09-10 18:24:35 info Update extension 'Stockholm 0.8.9'
2020-09-10 18:24:35 info Update extension 'Update 0.8.34'
2020-09-10 18:24:35 info Update extension 'Wiki 0.8.11'
2020-11-11 15:56:41 info Update extension 'Bundle 0.8.17'
2020-11-11 15:56:41 info Update extension 'Command 0.8.25'
2020-11-11 15:56:41 info Update extension 'Core 0.8.30'
2020-11-11 15:56:41 info Update extension 'Edit 0.8.38'
2020-11-11 15:56:41 info Update extension 'English 0.8.25'
2020-11-11 15:56:41 info Update extension 'French 0.8.25'
2020-11-11 15:56:41 info Update extension 'German 0.8.25'
2020-11-11 15:56:41 info Update extension 'Image 0.8.11'
2020-11-11 15:56:41 info Update extension 'Markdown 0.8.16'
2020-11-11 15:56:41 info Update extension 'Search 0.8.11'
2020-11-11 15:56:41 info Update extension 'Stockholm 0.8.10'
2020-11-11 15:56:41 info Update extension 'Update 0.8.42'
2020-11-11 15:56:41 info Update extension 'Wiki 0.8.13'
2020-11-11 15:56:42 info Convert settings files

**Comment by herula** [comment] 2020-11-11 16:03
The upper part is missing: 

2019-10-02 11:19:32 info Datenstrom Yellow 0.8.6, PHP 7.3.9-1~deb10u1, Apache Linux
2019-10-02 11:19:32 info Check Apache server configuration
2019-10-02 11:19:32 info Install language 'English'
2019-10-02 11:19:32 info Install language 'French'
2019-10-02 11:19:32 info Install language 'German'
2019-10-02 11:20:03 info Install extension 'Wiki 0.8.5'
2019-10-02 11:20:03 info Add user 'frank'
2019-10-02 16:19:30 info Install extension 'Wiki 0.8.5'
2019-10-02 16:39:55 info Install extension 'Helsinki 0.8.5'
2019-10-02 16:50:54 info Install extension 'Search 0.8.4'
2019-10-02 16:56:00 info Install extension 'Helsinki 0.8.5'
2019-10-02 17:38:02 info Install extension 'Wiki 0.8.5'
2019-10-02 18:33:07 info Install extension 'Wiki 0.8.5'
2019-10-02 22:49:34 info Install extension 'Private 0.8.3'

**Comment by markseu** [comment] 2020-11-11 16:08
I would have expect something like `Can't parse file '/system/layouts/navigation-search.html'` at the end of your log file. At least that's what should happen. I would active the debug mode and then you can see more information on the current page. See also https://datenstrom.se/yellow/help/troubleshooting#problems-after-update

**Comment by herula** [comment] 2020-11-11 18:05
Thank you. The debug output did not show any problem. If there was something wrong with file permissions, i think setting all to 777 should work ... but it doesn't. I also moved to another server with the same result. No big deal, i will copy .md and media files to a new installation. But I think that's not the way you want your updates to be delivered. ;-)

**Comment by markseu** [comment] 2020-11-11 18:09
Thanks for the feedback. It's hard to fix a problem without knowing what causes it. At the moment I am not sure what's causing update problems on some web servers. I am a maintainer for Datenstrom Yellow. Please [contact me](https://datenstrom.se/contact/) and I have a closer look.

**Comment by markseu** [comment] 2020-11-26 20:05
I did a couple of smaller changes to the automatic update process and it should be working better now. 

Let's close this issue and see if more problems are reported?

**Closed** 2020-12-11 09:39 UTC
